language: node_js
node_js:
  - 12
dist: trusty
sudo: required
branches:
  only:
    - master
    - develop
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test --code-coverage --watch=false --browsers=ChromeHeadless
  - ng build --prod --base-href "https://baryshevrs.github.io/ngrx-friends/"
after_success:
  ./node_modules/.bin/codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/ngrx-friends/
  on:
    branch: master
    node: 12
